inconsistent_names = ['Albany', "Mt St Mary's", "St. John's", 'N. Iowa', 'UNC-Ash.', 'FAU', 'Loyola Chi.',
                      'CCSU', 'Charleston', 'Loyola-Md.', 'Miami (Ohio)', 'E. Michigan',
                      'W. Michigan', 'George Wash.', 'N. Dak. St.', 'W. Carolina',
                      'Texas So.', 'N.J. Tech', 'Seattle', 'N. Mex. St.', 'LBSU',
                      'St. Fran.-Pa.','Clev. St.', 'Miss. St.', "Saint Mary's", 'Army', 'LMU',
                      'Va. Tech', 'USC', 'N.Carolina', 'Colo. St.']

cbs2ncaa = {
            'Albany': 'UAlbany',
            "Mt St Mary's": "Mount St. Mary's",
            "St. John's": "St. John's (NY)",
            'N. Iowa': 'UNI',
            'UNC-Ash.': 'UNC Asheville',
            'FAU': 'Fla. Atlantic',
            'Loyola Chi.': 'Loyola Chicago',
            'CCSU': 'Central Conn. St.',
            'Charleston': 'Col. of Charleston',
            'Loyola-Md.': 'Loyola Maryland',
            'Miami (Ohio)': 'Miami (OH)',
            'E. Michigan': 'Eastern Mich.',
            'W. Michigan': 'Western Mich.',
            'George Wash.': 'George Washington',
            'N. Dak. St.': 'North Dakota St.',
            'W. Carolina': 'Western Caro.',
            'Texas So.': 'Texas Southern',
            'N.J. Tech': 'NJIT',
            'Seattle': 'Seattle U',
            'N. Mex. St.': 'New Mexico St.',
            'LBSU': 'Long Beach St.',
            'St. Fran.-Pa.': 'Saint Francis (PA)',
            'Clev. St.': 'Cleveland St.',
            'Miss. St.': 'Mississippi St.', 
            "Saint Mary's":"Saint Mary's (CA)",
            'Army': 'Army West Point',
            'LMU': 'LMU (CA)',
            'Va. Tech': 'Virginia Tech',
            'USC': 'Southern California',
            'N. Carolina': 'North Carolina',
            'Colo St.': 'Colorado St.'

            
}