inconsistent_names = ['Albany', "Mt St Mary's", "St. John's", 'N. Iowa', 'UNC-Ash.', 'FAU', 'Loyola Chi.',
                      'CCSU', 'Charleston', 'Loyola-Md.', 'Miami (Ohio)', 'E. Michigan',
                      'W. Michigan', 'George Wash.', 'N. Dak. St.', 'W. Carolina',
                      'Texas So.', 'N.J. Tech', 'Seattle', 'N. Mex. St.', 'LBSU',
                      'St. Fran.-Pa.','Clev. St.', 'Miss. St.', "Saint Mary's", 'Army', 'LMU',
                      'Va. Tech', 'USC', 'N.Carolina', 'Colo. St.', 'McNeese St.', 'TX A&M-CC',
                      'La. Tech', 'Lamar', 'New Hamp.', 'Okla. St.', 'NC Central',
                      'San Fran.', 'Houston Chr.', 'C. Michigan', 'UL-Monroe', 'Tenn. Tech',
                      'Cal-Baker.', 'Incarnate Wood', 'SE Missouri St.', 'CS Fullerton', 'W. Kentucky',
                      'Jax. State', 'Nicholls St.', 'SC State', "St. Peter's", 'N. Alabam',
                      'SE Louisiana', 'Alcorn St.', 'Abilene Chr.', 'S. Dak. St.', 'SF Austin',
                      'CDNorthridge', 'So. Miss', 'N. Arizona', 'UCSB', 'N. Kentucky',
                      'Cent. Arkansas', 'N. Illinois', 'So. Utah', 'UMKC', 'E. Illinois',
                      'St. Bona.', 'E. Washington', 'NC A&T', 'Md.E. Shorer', 'Cal Baptsit',
                      'App. St.', 'UT-Rio Grande Valley', 'SC Upstate', 'Bethune-Cook.']

cbs2ncaa = {
            'Albany': 'UAlbany',
            "Mt St Mary's": "Mount St. Mary's",
            "St. John's": "St. John's (NY)",
            'N. Iowa': 'UNI',
            'UNC-Ash.': 'UNC Asheville',
            'FAU': 'Fla. Atlantic',
            'Loyola Chi.': 'Loyola Chicago',
            'CCSU': 'Central Conn. St.',
            'Charleston': 'Col. of Charleston',
            'Loyola-Md.': 'Loyola Maryland',
            'Miami (Ohio)': 'Miami (OH)',
            'E. Michigan': 'Eastern Mich.',
            'W. Michigan': 'Western Mich.',
            'George Wash.': 'George Washington',
            'N. Dak. St.': 'North Dakota St.',
            'W. Carolina': 'Western Caro.',
            'Texas So.': 'Texas Southern',
            'N.J. Tech': 'NJIT',
            'Seattle': 'Seattle U',
            'N. Mex. St.': 'New Mexico St.',
            'LBSU': 'Long Beach St.',
            'St. Fran.-Pa.': 'Saint Francis (PA)',
            'Clev. St.': 'Cleveland St.',
            'Miss. St.': 'Mississippi St.', 
            "Saint Mary's":"Saint Mary's (CA)",
            'Army': 'Army West Point',
            'LMU': 'LMU (CA)',
            'Va. Tech': 'Virginia Tech',
            'USC': 'Southern California',
            'N. Carolina': 'North Carolina',
            'Colo St.': 'Colorado St.',
            'McNeese St.': 'McNeese',
            'TX A&M-CC': 'A&M-Corpus Christi',
            'La. Tech': 'Lousiana Tech',
            'Lamar': 'Lamar University',
            'New Hamp.': 'New Hampshire',
            'Okla. St.': 'Oklahoma St.',
            'NC Central': 'N.C. Central',
            'San Fran.': 'San Franciso',
            'Houston Chr.': 'Houston Christian',
            'C. Michigan': 'Central Mich.',
            'UL-Monroe': 'ULM',
            'Miami': 'Miami (FL)',
            'Tenn. Tech': 'Tennessee Tech',
            'Cal-Baker.': ' CSU Bakersfield',
            'Incarnate Wood': 'IUW',
            'SE Missouri St.': 'Southeast Mo. St.',
            'CS Fullerton': 'Cal St. Fullerton',
            'W. Kentucky': 'Western Ky.',
            'Jax. State': 'Jacksonville St.',
            'Nicholls St.': 'Nicholls',
            'SC State': 'South Carolina St.',
            "St. Peter's": "Saint Peter's",
            'N. Alabama': 'North Ala.',
            'SE Louisiana': 'Southeastern La.',
            'Alcorn St.': 'Alcorn',
            'Abilene Chr.': 'Abilene Christian',
            'S. Dak. St.': 'South Dakota St.',
            'SF Austin': 'SFA',
            'CDNorthridge': 'CSUN',
            'So. Miss': 'Southern Miss.',
            'N. Arizona': 'Northern Ariz.',
            'UCSB': 'UC Santa Barbara',
            'N. Kentucky': 'Northern Ky.',
            'Cent. Arkansas': 'Central Ark.',
            'N. Illinois': 'NIU',
            'So. Utah': 'Southern U.',
            'UMKC': 'Kansas City',
            'E. Illinois': 'Eastern Ill.',
            'St. Bona.': 'St. Bonaventure',
            'E. Washington': 'Eastern Wash.',
            'NC A&T': 'N.C. A&T',
            'Md.E. Shorer': 'UMES',
            'Cal Baptsit': 'California Baptist',
            'App. St.': 'App State',
            'UT-Rio Grande Valley': 'UTRGV',
            'SC Upstate': 'USC Upstate',
            'Bethune-Cook.': 'Bethune-Cookman'

}